### ISSUE TITLE
KeyError: u'broadcast'  when convert onnx to caffe for resnet18

### ISSUE THREAD

**Issue by xmuszq** [YukiNagato/onnx2caffe#21]
the resnet18 in onnx is converted from mxnet. I want to convert this r18 in onnx to caffe. the error is listed below. Anything I can do to remove this error?

Traceback (most recent call last):
  File "convertCaffe.py", line 108, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 55, in convertToCaffe
    layer = converter_fn(node,graph,err)
  File "/home/zhen/Downloads/onnx2caffe/onnx2caffe/_operators.py", line 255, in _convert_gemm
    if node.attrs["broadcast"] != 1 or node.attrs["transB"] != 1:
KeyError: u'broadcast'

**Comment by cccober** [comment]
the same error!

**Comment by Hansoluo** [comment]
the same error! I just remove that line, it works...

**Comment by crouchggj** [comment]
In reference to url: https://github.com/onnx/onnx-tensorrt/issues/24, broadcast checking for opset ver > 7 should be removed.

**Comment by shopping-tang** [comment]
> the same error! I just remove that line, it works...

And you get a correct caffe model ?

**Comment by xiexu666** [comment]
Hi,i meet the same error,how did you solve this ? @shopping-tang @Hansoluo 
This url means to modify th onnx source code? @crouchggj

**Comment by shopping-tang** [comment]
> Hi,i meet the same error,how did you solve this ? @shopping-tang @Hansoluo
> This url means to modify th onnx source code? @crouchggj

emmm, it's been a while,  I've forgotten.Sorry.....
https://github.com/MTlab/onnx2caffe/issues/34, maybe you can take a look at this link.Hope it works for you.

**Comment by xiexu666** [comment]
> > Hi,i meet the same error,how did you solve this ? @shopping-tang @Hansoluo
> > This url means to modify th onnx source code? @crouchggj
> 
> emmm, it's been a while, I've forgotten.Sorry.....
> #34, maybe you can take a look at this link.Hope it works for you.
Thank for your reply.
