### ISSUE TITLE
ONNX node of type Transpose is not supported.

### ISSUE THREAD

**Issue by bachelorsins** [YukiNagato/onnx2caffe#22]
We are facing issues in converting model which has transpose convolution. Here are the details

`
Traceback (most recent call last):
  File "convertCaffe.py", line 108, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 52, in convertToCaffe
    err.unsupported_op(node)
  File "/home/nithish/code_space/python/onnx2caffe/onnx2caffe/_error_utils.py", line 36, in unsupported_op
    "ONNX node of type {} is not supported.\n".format(node.op_type,)
TypeError: ONNX node of type Transpose is not supported.
`

**Comment by YukiNagato** [comment]
Transpose operation is not supported in the official caffe @bachelorsins. If you want transpose operation, you may have to add it by yourself both in caffe and in this tool.

**Comment by zkj1995** [comment]
HELLO Have u slove the problem?

**Comment by DanielXu123** [comment]
Did you all trying convert modelo from keras to caffe?

**Comment by Wenboisstrong** [comment]
Have you solved this problem now ?@bachelorsins

**Comment by johnjunjun7** [comment]
> Did you all trying convert modelo from keras to caffe?

I'm converting the keras model. Have you tried it successfully?

**Comment by pustar** [comment]
I am facing the same problem, have you solved it ?

**Comment by bachelorsins** [comment]
No I have not solved the issue!
