### ISSUE TITLE
shufflenet v2 model onnx to caffe failed

### ISSUE THREAD

**Issue by wxhqw** [YukiNagato/onnx2caffe#39]
Traceback (most recent call last):
  File "convertCaffe.py", line 112, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 58, in convertToCaffe
    layer = converter_fn(node,graph,err)
  File "/data00/huqingwen.huqwen/workspace/npu/caffe2pb2tflite/gesture/hand-gestures/apu/pytorch2onnx2caffe2tf/onnx2caffe/_operators.py", line 194, in _convert_Reshape
    return err.unsupported_op_configuration(node, "Reshape dimention number shall be 2 or 4")
  File "/data00/huqingwen.huqwen/workspace/npu/caffe2pb2tflite/gesture/hand-gestures/apu/pytorch2onnx2caffe2tf/onnx2caffe/_error_utils.py", line 46, in unsupported_op_configuration
    "Error while converting op of type: {}. Error message: {}\n".format(node.op_type, err_message, )
TypeError: Error while converting op of type: Reshape. Error message: Reshape dimention number shall be 2 or 4

**Comment by northeastsquare** [comment]
@MTlab I also met this problem, when convert pytorch yolov3 to onnx, then convert to caffe
 我也遇到这个问题，在用yolov3转换到onnx, 再转换到caffe

**Comment by RichardSong-dev** [comment]
> @MTlab I also met this problem, when convert pytorch yolov3 to onnx, then convert to caffe
> 我也遇到这个问题，在用yolov3转换到onnx, 再转换到caffe

所以老哥问题解决了吗？我估计和你情况一样，pytorch->onnx->caffe。用opset9就报这个错，opset11在转upsample时报KeyError: 'height_scale'。

**Comment by songh11** [comment]
> > @MTlab I also met this problem, when convert pytorch yolov3 to onnx, then convert to caffe
> > 我也遇到这个问题，在用yolov3转换到onnx, 再转换到caffe
> 
> 所以老哥问题解决了吗？我估计和你情况一样，pytorch->onnx->caffe。用opset9就报这个错，opset11在转upsample时报KeyError: 'height_scale'。

请问有解决方法么，我pytorch1.5->onnx->caffe时也会报Reshape的错，在opset9时简化模型，会报Upsample的错
